version: '3.7'
services:
  # redis:
  #   image: redis:6.2-alpine
  #   container_name: redis
  #   restart: unless-stopped
  #   network_mode: bridge
  #   ports: 
  #     - 6379:6379

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    network_mode: bridge
    ports: 
      - 27017:27017

  api:
    build: .
    container_name: api
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 4000:4000
    command: npm run dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    links:
      # - redis
      - mongo